import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    appName: 'Iraq Compass',
    tagline: 'Your guide to the heart of Iraq',
    exploreCity: 'Explore my city',
    viewBusinesses: 'View businesses',
    seeTrending: "See what's trending",
    joinAsOwner: 'Join as business owner',
    baghdad: 'Baghdad',
    erbil: 'Erbil',
    basra: 'Basra',
    nineveh: 'Nineveh',
    duhok: 'Duhok',
    sulaymaniyah: 'Sulaymaniyah',
    kirkuk: 'Kirkuk',
    diyala: 'Diyala',
    anbar: 'Anbar',
    babil: 'Babil',
    karbala: 'Karbala',
    najaf: 'Najaf',
    qadisiyah: 'Qadisiyah',
    muthanna: 'Muthanna',
    dhiQar: 'Dhi Qar',
    maysan: 'Maysan',
    wasit: 'Wasit',
    salahAlDin: 'Salah al-Din',
    login: 'Login',
    logout: 'Logout',
    signUp: 'Sign Up',
    home: 'Home',
    dashboard: 'Dashboard',
    directory: 'Directory',
    stories: 'Stories',
    socialFeed: 'Community Feed',
    featured: 'Featured Businesses',
    events: 'Upcoming Events',
    deals: 'Exclusive Deals',
    postcards: 'Business Postcards',
    aiGuide: 'AI City Guide',
    aiGuideSubtitle: 'Ask our AI assistant anything about',
    aiGuidePlaceholder: 'Ask about',
    aiGuideConsulting: 'Consulting Local Experts...',
    aiGuideGathering: 'Our AI is gathering the best tips for',
    aiGuideClear: 'Clear Response',
    aiGuidePoweredBy: 'Powered by',
    aiGuideSuggestions: {
      restaurants: 'Best restaurants in',
      historical: 'Historical sites in',
      food: 'Local food specialties of',
      hidden: 'Hidden gems in'
    },
    guide: 'Guide',
    askAi: 'Ask me anything about Iraq...',
    send: 'Send',
    highContrast: 'High Contrast',
    language: 'Language',
    governorate: 'Governorate',
    verified: 'Verified',
    createPost: 'Create Post',
    ownerOnly: 'Only business owners can post.',
    ownerOnlyMessage: 'This feature is for business owners only.',
    joinAsOwnerToPost: 'Join as owner to post',
    emailComingSoon: 'Email login coming soon. Please use Google.',
    claimDeal: 'Claim Deal',
    registerEvent: 'Register',
    viewDetails: 'View Details',
    allGovernorates: 'All Governorates',
    search: 'Search...',
    noResults: 'No results found.',
    loading: 'Loading...',
    error: 'An error occurred.',
    profile: 'Profile',
    myBusiness: 'My Business',
    settings: 'Settings',
    back: 'Back',
    selectRole: 'Select your role',
    visitor: 'Visitor',
    businessOwner: 'Business Owner',
    continueWithGoogle: 'Continue with Google',
    comingSoon: 'Coming Soon',
    welcomeBack: 'Welcome back!',
    loggedOut: 'Successfully logged out.',
    ownerSignupPrompt: 'Please sign up as a business owner to post.',
    postCreated: 'Post created successfully!',
    categories: {
      restaurants: 'Restaurants',
      cafes: 'Cafes',
      hotels: 'Hotels',
      shops: 'Shops',
      services: 'Services',
      entertainment: 'Entertainment',
      automotive: 'Automotive',
      health: 'Health',
      education: 'Education',
      realEstate: 'Real Estate'
    }
  },
  ar: {
    appName: 'بوصلة العراق',
    tagline: 'دليلك إلى قلب العراق',
    exploreCity: 'استكشف مدينتي',
    viewBusinesses: 'عرض الشركات',
    seeTrending: 'شاهد ما هو رائج',
    joinAsOwner: 'انضم كصاحب عمل',
    baghdad: 'بغداد',
    erbil: 'أربيل',
    basra: 'البصرة',
    nineveh: 'نينوى',
    duhok: 'دهوك',
    sulaymaniyah: 'السليمانية',
    kirkuk: 'كركوك',
    diyala: 'ديالى',
    anbar: 'الأنبار',
    babil: 'بابل',
    karbala: 'كربلاء',
    najaf: 'النجف',
    qadisiyah: 'القادسية',
    muthanna: 'المثنى',
    dhiQar: 'ذي قار',
    maysan: 'ميسان',
    wasit: 'واسط',
    salahAlDin: 'صلاح الدين',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    signUp: 'اشتراك',
    home: 'الرئيسية',
    dashboard: 'لوحة القيادة',
    directory: 'الدليل',
    stories: 'قصص',
    socialFeed: 'تغذية المجتمع',
    featured: 'شركات مميزة',
    events: 'فعاليات قادمة',
    deals: 'عروض حصرية',
    postcards: 'بطاقات بريدية تجارية',
    aiGuide: 'دليل المدينة بالذكاء الاصطناعي',
    aiGuideSubtitle: 'اسأل مساعدنا الذكي أي شيء عن',
    aiGuidePlaceholder: 'اسأل عن',
    aiGuideConsulting: 'استشارة الخبراء المحليين...',
    aiGuideGathering: 'يقوم الذكاء الاصطناعي بجمع أفضل النصائح لـ',
    aiGuideClear: 'مسح الاستجابة',
    aiGuidePoweredBy: 'بدعم من',
    aiGuideSuggestions: {
      restaurants: 'أفضل المطاعم في',
      historical: 'المواقع التاريخية في',
      food: 'تخصصات الطعام المحلي في',
      hidden: 'الجواهر الخفية في'
    },
    guide: 'دليل',
    askAi: 'اسألني أي شيء عن العراق...',
    send: 'إرسال',
    highContrast: 'تباين عالٍ',
    language: 'اللغة',
    governorate: 'المحافظة',
    verified: 'موثق',
    createPost: 'إنشاء منشور',
    ownerOnly: 'يمكن لأصحاب الأعمال فقط النشر.',
    ownerOnlyMessage: 'هذه الميزة لأصحاب الأعمال فقط.',
    joinAsOwnerToPost: 'انضم كصاحب عمل للنشر',
    emailComingSoon: 'تسجيل الدخول بالبريد الإلكتروني قريباً. يرجى استخدام جوجل.',
    claimDeal: 'احصل على العرض',
    registerEvent: 'تسجيل',
    viewDetails: 'عرض التفاصيل',
    allGovernorates: 'جميع المحافظات',
    search: 'بحث...',
    noResults: 'لم يتم العثور على نتائج.',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ.',
    profile: 'الملف الشخصي',
    myBusiness: 'عملي',
    settings: 'الإعدادات',
    back: 'رجوع',
    selectRole: 'اختر دورك',
    visitor: 'زائر',
    businessOwner: 'صاحب عمل',
    continueWithGoogle: 'المتابعة مع جوجل',
    comingSoon: 'قريباً',
    welcomeBack: 'مرحباً بعودتك!',
    loggedOut: 'تم تسجيل الخروج بنجاح.',
    ownerSignupPrompt: 'يرجى التسجيل كصاحب عمل للنشر.',
    postCreated: 'تم إنشاء المنشور بنجاح!',
    categories: {
      restaurants: 'مطاعم',
      cafes: 'مقاهي',
      hotels: 'فنادق',
      shops: 'متاجر',
      services: 'خدمات',
      entertainment: 'ترفيه',
      automotive: 'سيارات',
      health: 'صحة',
      education: 'تعليم',
      realEstate: 'عقارات'
    }
  },
  ku: {
    appName: 'قیبلەی عێراق',
    tagline: 'ڕێبەری تۆ بۆ دڵی عێراق',
    exploreCity: 'شارەکەم بگەڕێ',
    viewBusinesses: 'بینینی کارەکان',
    seeTrending: 'ببینە چی باوە',
    joinAsOwner: 'وەک خاوەن کار بەشداری بکە',
    baghdad: 'بەغداد',
    erbil: 'هەولێر',
    basra: 'بەسرە',
    nineveh: 'نەینەوا',
    duhok: 'دهۆک',
    sulaymaniyah: 'سلێمانی',
    kirkuk: 'کەرکووک',
    diyala: 'دیالە',
    anbar: 'ئەنبار',
    babil: 'بابل',
    karbala: 'کەربەلا',
    najaf: 'نەجەف',
    qadisiyah: 'قادسیە',
    muthanna: 'موسەنا',
    dhiQar: 'زی قار',
    maysan: 'میسان',
    wasit: 'واست',
    salahAlDin: 'سەڵاحەدین',
    login: 'چوونەژوورەوە',
    logout: 'چوونەدەرەوە',
    signUp: 'تۆمارکردن',
    home: 'سەرەکی',
    dashboard: 'داشبۆرد',
    directory: 'ڕێبەر',
    stories: 'چیرۆکەکان',
    socialFeed: 'تەوەرەی کۆمەڵایەتی',
    featured: 'کارە دیارەکان',
    events: 'چالاکییە چاوەڕوانکراوەکان',
    deals: 'داشکاندنە تایبەتەکان',
    postcards: 'پۆستکارتە بازرگانییەکان',
    aiGuide: 'ڕێبەری شار بە ژیری دەستکرد',
    aiGuideSubtitle: 'هەر شتێک دەربارەی بپرسە لە یاریدەدەری ژیری دەستکردمان',
    aiGuidePlaceholder: 'بپرسە دەربارەی',
    aiGuideConsulting: 'ڕاوێژکردن بە شارەزایانی ناوخۆیی...',
    aiGuideGathering: 'ژیری دەستکردمان باشترین ئامۆژگارییەکان کۆدەکاتەوە بۆ',
    aiGuideClear: 'سڕینەوەی وەڵام',
    aiGuidePoweredBy: 'بەهێزکراوە لەلایەن',
    aiGuideSuggestions: {
      restaurants: 'باشترین چێشتخانەکان لە',
      historical: 'شوێنە مێژووییەکان لە',
      food: 'خواردنە تایبەتە ناوخۆییەکانی',
      hidden: 'گەوهەرە شاراوەکان لە'
    },
    guide: 'ڕێبەر',
    askAi: 'هەر شتێک دەربارەی عێراق بپرسە...',
    send: 'ناردن',
    highContrast: 'کۆنتراستی بەرز',
    language: 'زمان',
    governorate: 'پارێزگا',
    verified: 'پەسەندکراو',
    createPost: 'دروسکردنی پۆست',
    ownerOnly: 'تەنها خاوەن کارەکان دەتوانن پۆست بکەن.',
    ownerOnlyMessage: 'ئەم تایبەتمەندییە تەنها بۆ خاوەن بزنسەکانە.',
    joinAsOwnerToPost: 'وەک خاوەن کار بەشداری بکە بۆ پۆستکردن',
    emailComingSoon: 'چوونەژوورەوە بە ئیمەیڵ بەم زووانە دێت. تکایە گووگڵ بەکاربهێنە.',
    claimDeal: 'داواکردنی داشکاندن',
    registerEvent: 'تۆمارکردن',
    viewDetails: 'بینینی وردەکارییەکان',
    allGovernorates: 'هەموو پارێزگاکان',
    search: 'گەڕان...',
    noResults: 'هیچ ئەنجامێک نەدۆزرایەوە.',
    loading: 'بارکردن...',
    error: 'هەڵەیەک ڕوویدا.',
    profile: 'پڕۆفایل',
    myBusiness: 'کارەکەم',
    settings: 'ڕێکخستنەکان',
    back: 'گەڕانەوە',
    selectRole: 'ڕۆڵەکەت هەڵبژێرە',
    visitor: 'سەردانکەر',
    businessOwner: 'خاوەن کار',
    continueWithGoogle: 'بەردەوام بە لەگەڵ گووگڵ',
    comingSoon: 'بەم زووانە',
    welcomeBack: 'بەخێربێیتەوە!',
    loggedOut: 'بە سەرکەوتوویی چوویتە دەرەوە.',
    ownerSignupPrompt: 'تکایە وەک خاوەن کار خۆت تۆمار بکە بۆ پۆستکردن.',
    postCreated: 'پۆستەکە بە سەرکەوتوویی دروستکرا!',
    categories: {
      restaurants: 'چێشتخانەکان',
      cafes: 'کافێکان',
      hotels: 'هوتێلەکان',
      shops: 'دوکانەکان',
      services: 'خزمەتگوزارییەکان',
      entertainment: 'کات بەسەربردن',
      automotive: 'ئۆتۆمبێل',
      health: 'تەندروستی',
      education: 'پەروەردە',
      realEstate: 'خانووبەرە'
    }
  }
};
